import { createActionTypes } from "../utils";

export const USER = createActionTypes("USER", [
	"SIGNIN_REQUEST",
	"SIGNIN_SUCCESS",
	"SIGNIN_FAILED",
	"SIGNUP_REQUEST",
	"SIGNUP_SUCCESS",
	"SIGNUP_FAILED",
	"SIGNOUT",
	"SETMSG",
	"GETUSER_REQUEST",
	"GETUSER_SUCCESS",
	"GETUSER_FAILED"
]);

export const PRODUCT = createActionTypes("PRODUCT", [
	"ADDPRODUCT_REQUEST",
	"ADDPRODUCT_SUCCESS",
	"ADDPRODUCT_FAILED",
	"EDITPRODUCT_REQUEST",
	"EDITPRODUCT_SUCCESS",
	"EDITPRODUCT_FAILED",
	"DELETEPRODUCT_REQUEST",
	"DELETEPRODUCT_SUCCESS",
	"DELETEPRODUCT_FAILED",
	"SETSUCCESS",
	"GETPRODUCTS_REQUEST",
	"GETPRODUCTS_SUCCESS",
	"GETPRODUCTS_FAILED"
]);
